### ISSUE TITLE
Duplicate entries in root CA results in crash during connect

### ISSUE THREAD

**Issue by vishesh** [libressl-portable/openbsd#100]
If root CA file has duplicate entries in it, connect fails with following error: `ssl verify memory setup failure` https://github.com/libressl-portable/openbsd/blob/master/src/lib/libtls/tls.c#L516. 

I understand, root CA shouldn't have duplicates at first place, and this behavior may be intentional. However, the error we get out of this is not super helpful and can be more descriptive, so that it is easier/quicker to debug.

**Comment by 4a6f656c** [comment]
I believe this is fixed in the current LibreSSL releases - please let us know if this is not the case.
