### ISSUE TITLE
Deprecated option "-ssl" of RSA Utils is still listed in "--help" but "man"

### ISSUE THREAD

**Issue by KEINOS** [libressl-portable/openbsd#101]
It seems that "`-ssl`" option of RSA Utility (`rsautl`) command no longer exists in the manual.

```shellsession
$ man openssl 
...
RSAUTL
     openssl rsautl [-asn1parse] [-certin] [-decrypt] [-encrypt] [-hexdump] [-in
     file] [-inkey file] [-keyform der | pem] [-oaep | -pkcs | -raw] [-out file]
     [-pubin] [-sign] [-verify]
...
```

Of cource using this option gives us an error and shows the "`--help`" but it still exists in there.

```shellsession
$ openssl rsautl -encrypt -pubin -inkey id_rsa.pub.pkcs8 -ssl -in test.txt -out test.txt.enc
Usage: rsautl [options]
-in file        input file
-out file       output file
-inkey file     input key
-keyform arg    private key format - default PEM
-pubin          input is an RSA public
-certin         input is a certificate carrying an RSA public key
-ssl            use SSL v2 padding
-raw            use no padding
-pkcs           use PKCS#1 v1.5 padding (default)
-oaep           use PKCS#1 OAEP
-sign           sign with private key
-verify         verify with public key
-encrypt        encrypt with public key
-decrypt        decrypt with private key
-hexdump        hex dump output
```

On macOS this happens from today's update in Mojave.(Jan 29, 2019)

```
$ man openssl | tail -1
BSD                            January 29, 2019                            BSD
```

And even in the latest commit at the master branch there is (Line 321) :
https://github.com/libressl-portable/openbsd/blob/19a8bdc17a8fd67fe97e33f6d916108199cf376a/src/usr.bin/openssl/rsautl.c#L312-L330

<details><summary>ENV INFO</summary><div>

```shellsession
$ # macOS Mojave
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D42
$ openssl version
LibreSSL 2.6.5
$ man openssl | tail -1
BSD                            January 29, 2019                            BSD
```
</div></details>

**Comment by botovq** [comment]
On Tue, Jan 29, 2019 at 09:12:35AM +0000, KEINOS wrote:
> It seems that "`-ssl`" option of RSA Utility (`rsautl`) command no longer exists in the manual.

Indeed, thanks for the report. SSLv23 padding was removed in
[this commit][1], but `-ssl` was left behind in usage. Fixed in OpenBSD.
This will appear in this repo next time it is synced.


[1]: https://github.com/libressl-portable/openbsd/commit/286b2e2ae638bad06fdc2087d0bd938b0cb69375#diff-7cd392812913edd7bb9bc6354a2e43ef

**Comment by KEINOS** [comment]
@botovq 

> Fixed in OpenBSD. This will appear in this repo next time it is synced.

Thank you for the quick responce! I will close this issue as soon as it syncs then!

**Comment by KEINOS** [comment]
@botovq 
That was quick! Thanks!
https://github.com/libressl-portable/openbsd/commit/033f890a3c613623c454d0a44ac14130c8764dba#diff-7cd392812913edd7bb9bc6354a2e43efL321
