### ISSUE TITLE
Is libressl compatible with Linux?

### ISSUE THREAD

**Issue by philip-peterson** [libressl-portable/openbsd#117]
Hi there, I know the repository is called openbsd and all, but is `libressl` not compatible at all with Linux?

**Comment by kinichiro** [comment]
Hi,

LibreSSL portable version supports Linux platform, too.
You can see this on https://www.libressl.org/ .
You can also download portable source code tarball from "Download" link of https://www.libressl.org/ .

This repository pulls code from upstream OpenBSD for LibreSSL, that is why named 'openbsd'.
You can read this at "About" on https://github.com/libressl-portable/openbsd .
It doesn't mean "only for OpenBSD".

**Comment by philip-peterson** [comment]
Great, thanks for the information!
