### ISSUE TITLE
tls_keypair_load_cert() fail but return no error

### ISSUE THREAD

**Issue by rozhuk-im** [libressl-portable/openbsd#119]
```failed to load certificate: unknown: No error: 0```
This happen because https://github.com/libressl-portable/openbsd/blob/master/src/lib/libtls/tls_keypair.c#L140 must be ```unsigned long```

Fix:
```
--- src/lib/libtls/tls_keypair.c
+++ src/lib/libtls/tls_keypair.c
@@ -137,7 +137,7 @@
 {
 	char *errstr = "unknown";
 	BIO *cert_bio = NULL;
-	int ssl_err;
+	unsigned long ssl_err;
 	int rv = -1;
 
 	X509_free(*cert);
```

**Comment by kinichiro** [comment]
Upstream was fixed by this commit https://github.com/openbsd/src/commit/0431a4acb517d0e9bc5bb4dfd576ae7747e95590 .

**Comment by kinichiro** [comment]
Thanks for your report.
