### ISSUE TITLE
SSL_CTX_{g,s}et_security_level

### ISSUE THREAD

**Issue by steils** [libressl-portable/openbsd#120]
Some more OpenSSL methods missing in LibreSSL, needed to build QtNetwork, since 5.15.2.

https://code.qt.io/cgit/qt/qtbase.git/commit/?id=605d2163f1dcd7e1ad701ade913cb476b91865b1

**Comment by busterb** [comment]
Reason why this function is needed in QT strikes me as a bit odd; wonder why they didn't just make the test keys bigger. Security level 2 seems like a reasonable default these days (disable SSLv3), but I'm not sure any of the Levels in the SSL_get_security_level manpage match LibreSSL's default settings.

There are also a whole set of related callback and variant-on-a-theme functions, I guess so folks can hook everytime security level is changed. I wonder if we could get by with a bare minimum that ignores 'set' and always returns '2', as the closest approximation for now.

> CentOS it seems not only backported some OpenSSL 3 functions,
> but also raised the default security level to 2, making some of
> our keys (and MDs?) 'too weak' and failing auto-tests here and
> there as a result. For our auto-test we lower the level to 1,
>.as it is expected to be.

**Comment by 4a6f656c** [comment]
This will be available in the next LibreSSL release.

**Comment by 4a6f656c** [comment]
This API is available in LibreSSL 3.6.0.
