### ISSUE TITLE
URI Checks are too strict in subject alt name

### ISSUE THREAD

**Issue by ccvca** [libressl-portable/openbsd#131]
The OPC UA specification, requires certificates, which contain a subject_alt_name with an URI of the application. A valid URI might look like this: `urn:open62541.server.application`, wich is totally fine according to [rfc3986](https://datatracker.ietf.org/doc/html/rfc3986#section-1.1.2)

While updating the open source OPC UA implementation [open62541](https://github.com/open62541/open62541/) I noticed that the certificate generation breaks (e.g. (here)[https://github.com/open62541/open62541/blob/3706b2705f8305c3f648e30ed866a317b87a82e8/examples/encryption/server_encryption.c#L50] ), when setting the `NID_subject_alt_name`.
I traced this issue down to these lines:
https://github.com/libressl-portable/openbsd/blob/9ba7796bc3c2e069e32ded689df7a40d724da07b/src/lib/libcrypto/x509/x509_alt.c#L681-L688

There the URI is checked using `x509_constraints_uri_host`, but this function does only work for URIs which include `//`.

**Comment by botovq** [comment]
Thanks for the report.

I agree with you. `x509_constraints_uri_host()` only deals with the case that a SAN URI contains an authority and the additional restrictions imposed by RFC 5280 in that case. However, according to RFC 5280, 4.2.1.6, a SAN URI only needs a scheme and a scheme-specific part.

I do not know or remember if that was a deliberate choice or not. In any case, we should probably consider relaxing that.

@bob-beck, could you take a look?

**Comment by bob-beck** [comment]
Yeah, our behaviour here is incorrect. we are failing the parse of the URI in this case, but what we need to do is succeed, indicating that there is a URI with an empty host part, and then fail if we find URI name constraints in the certificate. 

I've got a candidate fix under review that does just that, and adds regress for this case. thanks for the report.

**Comment by GoetzGoerisch** [comment]
@bob-beck this fix did it not make into 3.6.1 is there a reason for?
