### ISSUE TITLE
Please consider removing `unsigned char*` strings from the API

### ISSUE THREAD

**Issue by mgorny** [libressl-portable/openbsd#21]
The original OpenSSL API used `unsigned char*` a lot for strings, and currently libressl does as well. While this is mostly harmless (warning-level at most) in C, this is kinda PITA for using libressl from C++ code.

Is there any particular reason for using it? String literals in both C and C++ are of plain `const char*` type. `char*` is used by standard C library I/O routines, ncurses, readline, glib (via `gchar`)… which pretty much means that the program is always required to convert `char*` to `unsigned char*` for libressl.

For example, the following is invalid in C++:

    X509_NAME_add_entry_by_txt(name, "O", MBSTRING_ASC, "foo", -1, -1, 0);

Because `"foo"` is `const char*`, you have to explicitly convert it to `const unsigned char*`. Which — strictly adhering to the standard — means allocating a new `unsigned char*` array and converting the original string byte-by-byte. Having libressl take standard `const char*` would be a blessing then.

**Comment by busterb** [comment]
Currently, the project tries to maintain a compatible API to OpenSSL as closely as possible.  This is an interesting idea though.

**Comment by bob-beck** [comment]
It's a very valid point..  and if we wanted to break the OpenSSL API, we could do this. 

consider using the libtls API instead.   Unfortunately I don't see a practical way to do this
without breaking existing users of the API.
