### ISSUE TITLE
O_DIRECTORY undeclared (certhash.c)

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/openbsd#23]
Hi,

I noticed that O_DIRECTORY isn't defined in hpux.

    ...
      CC       openssl-certhash.o
    certhash.c: In function 'certhash_main':
    certhash.c:661:25: error: 'O_DIRECTORY' undeclared (first use in this function)
    certhash.c:661:25: note: each undeclared identifier is reported only once for each function it appears in
    *** Error exit code 1

It seems that AIX doesn't have O_DIRECTORY, too.
http://marc.info/?l=openbsd-tech&m=142488231109861&w=2

Could you replace O_DIRECTORY with O_RDONLY ?

Thanks.

**Comment by busterb** [comment]
Done! c5196a5f20a6e35f3474afbe74cba376b4260728
