### ISSUE TITLE
openssl command usage output to stdout

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/openbsd#28]
Hi,

openssl command `errstr` and `s_time` usage messages are outputed to stdout.
all other commands output to stderr.

<pre>
# openssl errstr -help > /dev/null
#
# openssl errstr -help 2> /dev/null
-help: bad error code
usage: errstr [-stats] <errno> ...
#
</pre>

<pre>
# openssl s_time -help > /dev/null
unknown option -help
# openssl s_time -help 2> /dev/null
usage: s_time <args>

-connect host:port - host:port to connect to (default is localhost:4433)
-nbio         - Run with non-blocking IO
-ssl2         - Just use SSLv2
-ssl3         - Just use SSLv3
-bugs         - Turn on SSL bug compatibility
-new          - Just time new connections
-reuse        - Just time connection reuse
-www page     - Retrieve 'page' from the site
-time arg     - max number of seconds to collect data, default 30
-verify arg   - turn on peer certificate verification, arg == depth
-cert arg     - certificate file to use, PEM format assumed
-key arg      - RSA file to use, PEM format assumed, key is in cert file
                file if not specified by this option
-CApath arg   - PEM format directory of CA's
-CAfile arg   - PEM format file of CA's
-trusted_first - Use trusted CA's first when building the trust chain
-cipher       - preferred cipher to use, play with 'openssl ciphers'
#
</pre>

Thanks.

**Comment by 4a6f656c** [comment]
Thanks - errstr has been fixed (and converted to the new option handling) - a diff is out for review to give s_time the same treatment.

**Comment by 4a6f656c** [comment]
This is now also fixed for s_time - thanks for the report!

**Comment by kinichiro** [comment]
Thanks, I could see this issue was fixed.
