### ISSUE TITLE
openssl pkeyutl -verify returns exit status always 1

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/openbsd#29]
Hi,
openssl `pkeyutl -verify` command seems returns exit status always 1.
it should return exit status 0 when `pkeyutl -verify` succeeds.

<pre>
# openssl_bin=/work/github/portable/apps/openssl
# $openssl_bin pkeyutl -verify -in pkeyutl.dat -sigfile pkeyutl.sig -inkey genpkey_rsa.pem
Signature Verified Successfully
# echo $?
1
#
# $openssl_bin pkeyutl -verify -in pkeyutl.dat -sigfile pkeyutl.sig -inkey genrsa_aes256.pem
Enter pass phrase for genrsa_aes256.pem:
Signature Verification Failure
# echo $?
1
#
</pre>

Thanks.

**Comment by kinichiro** [comment]
Sorry, this was already reported by this.
http://rt.openssl.org/Ticket/Display.html?user=guest&pass=guest&id=2618

**Comment by 4a6f656c** [comment]
This should be fixed in -current (pkeyutl.c r1.5).

**Comment by kinichiro** [comment]
I could confirm this issue is fixed in current.
Thank you.
