### ISSUE TITLE
Test biotest failing on FreeBSD

### ISSUE THREAD

**Issue by Sp1l** [libressl-portable/openbsd#35]
Seems like inet_pton() behaves differently on FreeBSD compared to OpenBSD

FAIL: test 2 ("1") success, want failure
FAIL: test 3 ("1.2") success, want failure
FAIL: test 4 ("1.2.3") success, want failure
FAIL: test 13 ("0xff.0xff.0xff.0xff") success, want failure
FAIL biotest (exit status: 1)

**Comment by busterb** [comment]
True. IIRC the results vary over other OSes as well, which is why LibreSSL portable does not enable this test by default. I've thought about including the OpenBSD inet_pton in the compat layer for the sake of consistency.

**Comment by kinichiro** [comment]
biotest results of other platforms, here.
I built biotest by `./configure --enable-extratests`.

- HP-UX 11i (both gcc and C/aC++)
FAIL: test 2 ("1") success, want failure
FAIL: test 3 ("1.2") success, want failure
FAIL: test 4 ("1.2.3") success, want failure
FAIL: test 11 ("imaps") failure, want success
FAIL biotest (exit status: 1)

- CentOS7
FAIL: test 2 ("1") success, want failure
FAIL: test 3 ("1.2") success, want failure
FAIL: test 4 ("1.2.3") success, want failure
FAIL: test 1 ("") success, want failure
FAIL biotest (exit status: 1)

- Solaris 11.2 i386
FAIL: test 2 ("1") success, want failure
FAIL: test 3 ("1.2") success, want failure
FAIL: test 4 ("1.2.3") success, want failure
FAIL: test 13 ("0xff.0xff.0xff.0xff") success, want failure
FAIL: test 1 ("") success, want failure
FAIL: test 11 ("imaps") failure, want success

- Cygwin64
FAIL: test 0 ("") success, want failure
FAIL: test 1 ("") success, want failure
FAIL biotest.exe (exit status: 1)

- MinGW64
FAIL: test 11 ("localhost") failure, want success
FAIL: test 11 ("imaps") failure, want success

**Comment by Sp1l** [comment]
The difference between OpenBSD's and FreeBSD's inet_pton4 is very small and both descend from isc/Paul Vixie's code.
POSIX states that the test should fail when there's fewer or more than 4 octets in the input and FreeBSD code indicates this behaviour as well. 
[FreeBSD inet_pton.c](https://svnweb.freebsd.org/base/releng/10.1/lib/libc/inet/inet_pton.c?revision=272461&view=markup)
```
@@ -92,16 +84,14 @@
                if ((pch = strchr(digits, ch)) != NULL) {
                        u_int new = *tp * 10 + (pch - digits);

-                       if (saw_digit && *tp == 0)
-                               return (0);
                        if (new > 255)
                                return (0);
-                       *tp = new;
-                       if (!saw_digit) {
+                       if (! saw_digit) {
                                if (++octets > 4)
                                        return (0);
                                saw_digit = 1;
                        }
+                       *tp = new;
                } else if (ch == '.' && saw_digit) {
                        if (octets == 4)
                                return (0);
```

**Comment by bob-beck** [comment]
In a nutshell, the test requires a posix compliant inet_pton().  We will simply disable
the test on systems that do not have this.
