### ISSUE TITLE
RAND engine support removed

### ISSUE THREAD

**Issue by therth** [libressl-portable/openbsd#36]
LibreSSL uses arc4random for random number generation. The way this has been implemented, i.e. replacing the calls to RAND_bytes and RAND_pseudo_bytes by a call to arc4random, removed the support for a custom RAND engine, because there is no code anymore which calls the functions of the RAND engine provided by ENGINE_set_RAND and ENGINE_set_default(e, ENGINE_METHOD_RAND).

Was the removal of RAND engine support intended?

**Comment by tedu** [comment]
Yes. There is only one rand generator now.
