### ISSUE TITLE
libtls - fragile SSL_read()=0

### ISSUE THREAD

**Issue by markokr** [libressl-portable/openbsd#44]
I have a testcase where EOF from SSL_read() will be converted to random error because the random error was in global libssl error stack.  The problem is that libssl does not touch error stack when returning 0.

The actual testcase was actually on openssl 1.1, does not reproduce on libressl or openssl 1.0.1/2.

But the same coding is visible in libressl too.  Should libtls be more robust against it?  Call ERR_clear_error() in tls_read() / tls_write() / tls_handshake() ?

**Comment by 4a6f656c** [comment]
The only time libtls calls ERR_* is if we got a SSL_ERROR_SYSCALL or SSL_ERROR_SSL error code. I would think that calling ERR_* on EOF is actually the wrong thing to be doing.

**Comment by markokr** [comment]
Well, thats how SSL_read()=0 is documented:

> Call SSL_get_error() with the return value ret to find out, whether an error occurred or the connection was shut down cleanly (SSL_ERROR_ZERO_RETURN).

Either libssl always calls SSLerr() when it return 0, or libtls needs to clear error before calling SSL_read().

Alternative is also not to look at error on '0' return , always assume it's EOF.  I suspect this may  be quite popular solution.

**Comment by markokr** [comment]
It is reproducible with libressl too - just put:

  SSLerr(SSL_F_SSL3_CONNECT, SSL_R_COOKIE_MISMATCH); 

before calling tls_read() and see what happens.

**Comment by bob-beck** [comment]
I'm laughing at Joel, and he's crying..

we'll clear it..

**Comment by 4a6f656c** [comment]
Fixed, thanks.
