### ISSUE TITLE
Mismatched reference counting in SSL_new()

### ISSUE THREAD

**Issue by Parakleta** [libressl-portable/openbsd#51]
Found this while reading the code, not through testing.  The reference count on the `ctx` structure is incremented for the assignment of `ctx` to `s->initial_ctx` but this is not decremented on the code path through the `err:` label.  The increment/decrement is matched for the assignment of `ctx` to `s->ctx`.

[ssl_lib.c](https://github.com/libressl-portable/openbsd/blob/37759485f52993eb812898ccd70fc42cd92cdad5/src/lib/libssl/src/ssl/ssl_lib.c#L332-L368).

**Comment by hogand** [comment]
Thanks!  Fixed in -current.
