### ISSUE TITLE
Varying declarations of BN_print

### ISSUE THREAD

**Issue by pascal-cuoq** [libressl-portable/openbsd#53]
The header `bn.h` defines the function `BN_print` differently depending whether `bio.h` is [included:](https://github.com/libressl-portable/openbsd/blob/31597b44c1c231ca6969ee8455adbbb7098d3440/src/lib/libssl/src/crypto/bn/bn.h#L436-L440)

```
#ifdef HEADER_BIO_H
int	BN_print(BIO *fp, const BIGNUM *a);
#else
int	BN_print(void *fp, const BIGNUM *a);
#endif
```

Only one type is allowable for `BN_print`, the type with which the function is defined (C11 6.2.7:2 “All declarations that refer to the same object or function shall have compatible type; otherwise, the behavior is undefined”). The types `void *` and `BIO *` are not compatible, and neither are the types of functions taking one or the other as argument.

Does anyone know what problem the hack above is supposed to solve and whether it is still useful?

**Comment by bob-beck** [comment]
Whatever it was meant to solve in the 90's doesn't matter anymore... Let's just include the proper header ahead of time..  fixed in tree..
