### ISSUE TITLE
Null pointer dereference: bn_wexpand return code not checked in bn_g2fm.c

### ISSUE THREAD

**Issue by pascal-cuoq** [libressl-portable/openbsd#56]
The function `bn_wexpand()` can fail. Most of the invocations in bn_g2fm.c are guarded, but three of them aren't, causing a null pointer dereference when `bn_wexpand()` fails:

https://github.com/libressl-portable/openbsd/blob/80e93e1153038e48e7bdb4236e9174f91b6375dd/src/lib/libssl/src/crypto/bn/bn_gf2m.c#L705

Courtesy of GitHub search, this other group of calls in ec2_mult.c is also suspicious:

https://github.com/libressl-portable/openbsd/blob/37759485f52993eb812898ccd70fc42cd92cdad5/src/lib/libssl/src/crypto/ec/ec2_mult.c#L292

**Comment by 4a6f656c** [comment]
This was fixed some time ago.
