### ISSUE TITLE
Support "SSL_CTX_set1_curves_list"

### ISSUE THREAD

**Issue by fancycode** [libressl-portable/openbsd#58]
It would be nice if LibreSSL could support `SSL_CTX_set1_curves_list` which is required to allow a server to specify a list of curves to use for ECDH temporary key generation (for example here: http://mailman.nginx.org/pipermail/nginx-devel/2014-April/005234.html)

I know that LibreSSL was forked from OpenSSL 1.0.1 and the feature was added in 1.0.2 - are there any plans to backport this?

**Comment by longsleep** [comment]
Now that Chrome 50 is soon to be released (with support for Curve25519/X25519) it would be nice if LibreSSL servers with this curve would be possible rather sooner than later. See also https://github.com/libressl-portable/portable/issues/114 for general Curve25519/X25519 support in LibreSSL.

**Comment by pouar** [comment]
It would be nice if LibreSSL supported this, as this is literally the only thing keeping me on OpenSSL for my web server. If anyone knows how I can specify a list of curves without it, even if it means modifying LibreSSL to hard code this and have it statically compiled, please let me know

**Comment by 4a6f656c** [comment]
@pouar see eccurves_default in libssl/t1_lib.c (currently line 253).

**Comment by pouar** [comment]
found the problem, nginx seems to only call SSL_CTX_set_ecdh_auto only when it supports SSL_CTX_set1_curves_list, otherwise it will set it to prime256v1. I modified it so it always uses SSL_CTX_set_ecdh_auto

**Comment by 4a6f656c** [comment]
This is a dup of issue #33.
