### ISSUE TITLE
Failure to report EOF during handshake

### ISSUE THREAD

**Issue by markokr** [libressl-portable/openbsd#59]
Problem: https://marc.info/?l=libressl&m=145523606005224&w=4

Fix: https://marc.info/?l=libressl&m=145546713518505&w=4

**Comment by bob-beck** [comment]
We are really really really wanting to avoid the OpenSSL model of "set an error string and have someone look at it after". it's been the cause of a lot of pain we don't want to see in the libtls api.  

So, I'm not averse to thinking about a solution to this little issue, but not at the expense of
reintroducing "error strings" - we need a better way.

**Comment by 4a6f656c** [comment]
A slightly different version of this fix was committed in tls.c r1.39 - thanks.
