### ISSUE TITLE
A way to Block a single CA. Example: Blue Coat Public Services Intermediate CA

### ISSUE THREAD

**Issue by MercSec** [libressl-portable/openbsd#60]
Related to https://crt.sh/?id=19538258 Blue Coat got signed as CA by Verisign. Since dropping Verisin is not a good idea I like to block the Blue Coat CA/Cert. Blue Coat offers MITM Devices so some users might wish to Block specific Certificates or CAs. Maybe it is also a good choice to disallow such Vendors by default so people/users need to activate them.

After reading the manpage I did not found a way to block a specific sub-CA.
Revoking won't work (I am now the owner of the Certificate) and removing Verisign might not be such a good idea.

In case there is a method I did not spot: please point it out, otherwise I consider it a missing feature/Bug. It would be nice if there is a default-file where you can insert Certificates you like NOT to trust (even if they are valid and signed by a trusted CA).

Kind regards,
Sebastian Rother

**Comment by kinichiro** [comment]
Hi,

Does `-untrusted` option of `openssl verify` command solve your issue ?

Regards,

**Comment by MercSec** [comment]
I can not  test it anymore (no access to the network with such a Cert! :( ) but even if true: I seek to "untrust" all signed Certificates by this CA as well! Related to the man-page I am unsure if this Option handles this case. If somebody could test it (from the Devs) and either tell me I am wrong or right (by claiming we need a more simple way to "UNTRUST" such Certs) i'd be thankfull.

I just claimed: As I needed a solution: I did not found one by reading the manpage.. would the "untrust"-Solution solve the Issue I explained?!

Kind regards,
Sebastian Rother

**Comment by MercSec** [comment]
Related to Stuart Henderson it is not possible to Blog it in a sane way.

http://marc.info/?l=openbsd-misc&m=146469866805382&w=2

I would like to "convert" it to a Feature request. It would be kind if there is a way to archive such things in a easy way (Serverwide, so all Services using LibreSSL simply deny the Certificate as well).

Kind regards,
Sebastian Rother

**Comment by bob-beck** [comment]
Sebastien, please go away.

There is a reason you can't post to the OpenBSD lists. Just please stop.

Thank you

-Bob

**Comment by MercSec** [comment]
I just made a Feature request since this could be usefull for many users.
Why should somebody ask about such a Function at the Mailinglists anyway? I just noticed the answer and thus the ack' that you can not Block a bad Sub-CA. This might be worth getting considered.
