### ISSUE TITLE
LibreSSL server with SNI ignores client signature algorithms and only signs SHA-1

### ISSUE THREAD

**Issue by davidben** [libressl-portable/openbsd#69]
Short version: Please import this change from OpenSSL
https://git.openssl.org/gitweb/?p=openssl.git;a=commit;h=4e05aedbcab7f7f83a887e952ebdcc5d4f2291e4

It appears LibreSSL never imported the 2014 OpenSSL fix above. See https://rt.openssl.org/Ticket/Display.html?id=3560 for the original report which includes repro instructions. Note you may need an OpenSSL 1.0.2 build for the s_client half of the repro steps. Unless you all backported it, OpenSSL 1.0.1, which you're based on, does not print the peer signature algorithm in s_client.

The failure mode is LibreSSL servers which use SNI are only capable of signing SHA-1 hashes when producing the ServerKeyExchange. Such servers will break against clients which require stronger ServerKeyExchange signatures. (I noticed this looking for SHA-1-requiring servers in the wild. Turned out some of it was because of LibreSSL.)

PS: The proper fix here is actually to revise the state-tracking so peer sigalgs are not on the `CERT` struct. The latest revisions of both OpenSSL and BoringSSL have moved it elsewhere, so that may be some follow-up cleanup to be done here. But that code has changed significantly since 1.0.1 so importing the fix first may be simplest.

**Comment by kinichiro** [comment]
I sent the patch to tech ML. http://marc.info/?t=147392361300004&r=1&w=2

**Comment by busterb** [comment]
Applied, thanks: c2f8e0c15b8c5da6f28e5c2eb806acfdaf300557
