### ISSUE TITLE
is there a way to detect the release date of a libressl/libtls dylib/so?

### ISSUE THREAD

**Issue by cartazio** [libressl-portable/openbsd#70]
in some of the applications i'm involved in writing (as well as the haskell binding i'm still WIP on), I want to provide the option / ability to either issue warning on STDERR or refuse to run outright if the dynamic/shared library isn't recent enough in time (eg, >1 or perhaps 2 years?)

either way, this information seems to only be available in the headers, and not runtime, presently. (or my understanding it out of date :) )

**Comment by 4a6f656c** [comment]
This is not currently supported and I'm not convinced this is something that the library should provide.
