### ISSUE TITLE
arc4random_buf() segfaults on MIPS32 with uClibc-0.9.33.2.

### ISSUE THREAD

**Issue by nihilus** [libressl-portable/openbsd#78]
arc4random_buf() segfaults on MIPS32 with uClibc-0.9.33.2 and Linux.

**Comment by 4a6f656c** [comment]
Unfortunately we'll need more than this to investigate/resolve - can you please provide sample code and a back trace?

**Comment by nihilus** [comment]
@4a6f656c Yeah, it might be due to a buggy pthreads implementation or whatever; however porting the arc4random_buf() function to uClibc resolves this problem.

I guess other people might find this useful.

**Comment by 4a6f656c** [comment]
@nihilus - thanks, if we can get a trace we might be able to isolate the problem, without that there's not much we can do. Since you have a workaround, I'll close this - please reopen if further information can be provided.
