### ISSUE TITLE
Q: Should leaks found with leak sanitizer in tests/regress be fixed?

### ISSUE THREAD

**Issue by tamersaadeh** [libressl-portable/openbsd#81]
For example on [this line](https://github.com/libressl-portable/openbsd/blob/d884d1f143d65bc611980fcffaa9caafc7fdd6c2/src/regress/lib/libcrypto/exp/exptest.c#L228) one of the `BN_new()` might not be freed. There are other examples. Are patches needed? If not close this and sorry for the noise.

(PS: I have a `Dockerfile` with this config based on Ubuntu that I can share if necessary)

**Comment by 4a6f656c** [comment]
The short answer is yes.

The longer answer is that test and regress code tend to be looked at by people who are wanting to write real code, so ensuring that it is written correctly is beneficial. As you note, it also helps to find real issues with analysers/sanitisers, when there is not undo noise.
