### ISSUE TITLE
compile openssl failed

### ISSUE THREAD

**Issue by multiSnow** [libressl-portable/openbsd#85]
Since commit f4017f42493f468fc323a37093edefb9a0f24020:
```
apps_posix.o:apps_posix.c:function app_timer_real: error: undefined reference to 'timespecsub'
```
build Linux 4.14.0-1-amd64 with gcc 7.2.1

Is timespecsub really exists in linux?

**Comment by busterb** [comment]
Make an issue (or patch) on portable please, this is just a mirror of the current OpenBSD CVS tree.

**Comment by busterb** [comment]
I'll fix this on the portable branch soon. There are some other issues beyond this one.
