### ISSUE TITLE
CWE-327

### ISSUE THREAD

**Issue by RootUp** [libressl-portable/openbsd#93]
Hi Team, 

This issue was observed while doing source code analysis that:

`https://github.com/libressl-portable/openbsd/blob/master/src/lib/libcrypto/evp/e_old.c#L83` 

DES only supports a 56-bit keysize, which is too small given today'scomputers such as (CWE-327). 

I think using a different patent-free encryption algorithm with a larger keysize, such as 3DES or AES.

Request team, to have a look.

Cheers!

**Comment by 4a6f656c** [comment]
What is it exactly, that you think this code actually does?

**Comment by RootUp** [comment]
My bad, I just had a look on `https://github.com/libressl-portable/openbsd/blob/master/src/lib/libcrypto/evp/e_old.c#L135` and below
Closing this issue.
